### ISSUE TITLE
(Privacy) Blocking of elements does not work

### ISSUE THREAD

**Issue by kerwitz** [rrweb-io/rrweb-snapshot#3]
As per the [docs of the master repo](https://github.com/rrweb-io/rrweb/blob/master/guide.md#privacy) elements with `.rr-block` should not be recorded. I have two different scenarios where this does not seem to apply at all.

**Updating text contents**

```
<span id="random" class="rr-block"></span>

setInterval(() => document.getElementById('random').innerText = Math.random(), 1000);
```

The same applies when updating child nodes of the `.rr-block` element. 

I observe events being collected for these changes (by console.logging them). This should not be happening I guess?

According to [the code](https://github.com/rrweb-io/rrweb-snapshot/blob/master/src/snapshot.ts#L101) the `.rr-block` class seems to be only checked against the mutated element itself, not its parents. I realize this may be unfeasible to do on every mutation, but if an element is marked as "private" I would expect this to propagate to any of its children as well.

I am yet to dive deeper into these problems but it may turn out to be better to split this up into two separate issues (text node blocking and private child nodes).

**Comment by Yuyz0112** [comment]
I think I get the point and will check this again later, looks like a bug.

**Comment by Yuyz0112** [comment]
The [current code](https://github.com/rrweb-io/rrweb-snapshot/blob/master/src/snapshot.ts#L215) will also block the child node by skipping serialization.

This bug happened because we are not checking whether a newly added node has an ancestor node which is blocked, and in your sample code a text node was added and tracked.
If you write code like this you will find child nodes were blocked:
```diff
- <span id="random" class="rr-block"></span>
+ <span id="random" class="rr-block">1</span>

setInterval(() => document.getElementById('random').innerText = Math.random(), 1000);
```

This bug will be fixed in the rrweb repo since the observer code was there, and also will add an improvement of not emit empty events.

**Comment by Yuyz0112** [comment]
fixed in https://github.com/rrweb-io/rrweb/commit/8f24cb78b3ced58243906b476affeddc570ac232
